# Generated by Django 4.1.7 on 2023-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=200)),
                ('team_level', models.CharField(choices=[('u01', 'top1'), ('u02', 'top2')], default='u03', max_length=5)),
            ],
        ),
    ]
